name: Deploy Next.js site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  pull_request:

jobs:
  docker:
  runs-on: ubuntu-latest
  steps:
    -name: Build and push Docker image
      uses: docker/setup-qemu-action@v3
      with:
        context:.
        file:./Dockerfile
        tags: ghcr.io/username_0/next-js-pages:latest
        push: true
      
